


export const LOGIN_EXCEPTION = 'LOGIN_EXCEPTION'

export const CURRENT_USER_POSTS_UPDATE = 'CURRENT_USER_POSTS_UPDATE'
export const CHATS_SET = 'CHATS_SET'


export const MODAL_OPEN_COMMENT_SECTION = 'MODAL_OPEN_COMMENT_SECTION'
export const CLEAR_MODAL = 'CLEAR_MODAL'

export const SEARCH_API_EXCEPTION = 'SEARCH_API_EXCEPTION'
export const BASE_URL = 'http://localhost:8888';



export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'

export const REGISTER_EXCEPTION = 'REGISTER_EXCEPTION'

export const SEARCH_USER_EXCEPTION = 'SEARCH_USER_EXCEPTION'